# Generated by Django 4.2.20 on 2025-04-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('uom', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='project.project')),
            ],
        ),
    ]
