# Generated by Django 4.2.20 on 2025-05-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order_details', '0001_initial'),
        ('project', '0001_initial'),
        ('delivery_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_order_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery_order_details.deliveryorderdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='uom',
            field=models.CharField(choices=[('each', 'EA'), ('m', 'M')], max_length=50),
        ),
    ]
