# Generated by Django 4.2.20 on 2025-04-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_no', models.CharField(max_length=50)),
                ('po_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('project_location', models.CharField(max_length=200)),
                ('attn_to', models.CharField(max_length=100)),
                ('project_codename', models.CharField(max_length=100)),
                ('declaration', models.CharField(max_length=200)),
                ('delivery_location', models.CharField(max_length=200)),
                ('delivery_order_percentage', models.IntegerField()),
                ('delivery_company_name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_details', to='project.project')),
            ],
        ),
    ]
