# Generated by Django 4.2.20 on 2025-04-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_no', models.FloatField()),
                ('job_description', models.CharField(max_length=200)),
                ('uom', models.CharField(max_length=150)),
                ('unit_rate', models.FloatField()),
                ('quantity', models.FloatField()),
                ('boq_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to='project.project')),
            ],
        ),
    ]
