# Generated by Django 4.2.20 on 2025-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=50)),
                ('project_start_date', models.DateField()),
                ('project_complete_date', models.DateField()),
            ],
        ),
    ]
