# Generated by Django 4.2.20 on 2025-05-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('invoice_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetails',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='account',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice_percentage',
            field=models.IntegerField(choices=[(20, '20%'), (30, '30%'), (50, '50%')]),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
