# Generated by Django 4.2.20 on 2025-04-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('specification', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('supplier', models.CharField(max_length=200)),
                ('contact_no_supplier', models.CharField(max_length=50)),
            ],
        ),
    ]
