# Generated by Django 4.2.20 on 2025-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='specification',
            field=models.CharField(choices=[('manhole', 'Manhole'), ('manhole accessories', 'Manhole Accessories'), ('fiber accessories', 'Fiber Accessories'), ('cable', 'Cable'), ('pipe & ducting', 'Pipe & Ducting'), ('pole', 'Pole'), ('pole accessories', 'Pole Accessories'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('m', 'M'), ('roll', 'Roll'), ('lgth (6m)', 'Length(6m)'), ('coil', 'Coil'), ('set', 'Set')], max_length=50),
        ),
    ]
