# Generated by Django 4.2.20 on 2025-04-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('specification', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_ordered_unit_price', models.FloatField()),
                ('quantity_stock', models.IntegerField()),
                ('quantity_stock_unit_price', models.FloatField()),
                ('quantity_stock_acquired_from_site_name', models.CharField(max_length=250)),
                ('supplier', models.CharField(max_length=200)),
                ('contact_no_supplier', models.CharField(max_length=50)),
                ('delivery_method', models.CharField(max_length=50)),
                ('delivery_details', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bester_inventories', to='project.project')),
            ],
        ),
    ]
