# Generated by Django 4.2.20 on 2025-05-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('external_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalinventory',
            name='delivery_method',
            field=models.CharField(choices=[('delivery to site', 'Delivery to site'), ('pick up', 'Pick Up'), ('external w house', 'External Warehouse')], max_length=50),
        ),
        migrations.AlterField(
            model_name='externalinventory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='externalinventory',
            name='specification',
            field=models.CharField(choices=[('manhole', 'Manhole'), ('manhole accessories', 'Manhole Accessories'), ('fiber accessories', 'Fiber Accessories'), ('cable', 'Cable'), ('pipe & ducting', 'Pipe & Ducting'), ('pole', 'Pole'), ('pole accessories', 'Pole Accessories'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='externalinventory',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('m', 'M'), ('roll', 'Roll'), ('lgth (6m)', 'Length(6m)'), ('coil', 'Coil'), ('set', 'Set')], max_length=50),
        ),
    ]
