# Generated by Django 4.2.20 on 2025-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_inventory', '0002_alter_externalinventory_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalinventory',
            name='ordered',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
